version: '3.8'
services:
  minio-test:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: access
      MINIO_ROOT_PASSWORD: secretsecret
    ports:
      - "9002:9000"
    command: server /data
